### ISSUE TITLE
[Minimig-AGA core] Bar / stripes pattern in dark backgrounds

### ISSUE THREAD

**Issue by mambrino** [mist-devel/mist-binaries#29]
Hi,

I found an annoying problem with minimig-AGA core v1.2. With scandoubler activated in dark consistent color backgrounds a kind of vertical bars/stripes pattern appears. I've tried this with Minimig board and doesn't occur.

Here is a picture in which you can see the effect (Demo: Enjoy The Silents / WHDLoad & ADF):

![mist](https://cloud.githubusercontent.com/assets/19496893/17110523/b530a0e2-529d-11e6-9999-dbd6cb2669cb.jpg)

And this is with minimig board (no problem):

![minimig](https://cloud.githubusercontent.com/assets/19496893/17110529/bf611d26-529d-11e6-8f31-3be198a7d381.jpg)

Tested with different cables / monitors, and it's not a problem related to this.

Thanks ;)

**Comment by rkrajnc** [comment]
Which core version are you using? 
If this is not a new issue, it should be fixed in the latest release,. Do you have dither enabled?

**Comment by mambrino** [comment]
Minimig-AGA v.1.2
I've tested with & without dither / loRes-hiRes filters and problem persists.

Thanks ;)
